apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-slack-url
  namespace: {{.Release.Namespace}}
  labels:
{{- include "python-message-slack.labels" .  | nindent 4 }}
type: Opaque
data:
  slack_url: {{ .Values.slackSecret.url }}